# generated by `husk --print-completion=bash` -- do not hand-edit; regenerate with that command whenever export's flag table changes.
_husk_completions() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local subcommands="export info dump-chunks"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$subcommands" -- "$cur"))
        return
    fi

    case "${COMP_WORDS[1]}" in
        export)
            case "$prev" in
                --input|-i)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --output|-o)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --skin|-s)
                    COMPREPLY=($(compgen -W "auto" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -f -- "$cur"))
                    return
                    ;;
                --textures|-t)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --textures-out)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --skin-dir)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --anim|-a)
                    COMPREPLY=($(compgen -W "auto inline none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --skel)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -f -- "$cur"))
                    return
                    ;;
                --lod)
                    COMPREPLY=($(compgen -W "all" -- "$cur"))
                    return
                    ;;
                --bones-dir)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --phys)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -f -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --input -i --output -o --skin -s --textures -t --textures-out --skin-dir --anim -a --skel --lod --bones-dir --phys --collision" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        info)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        dump-chunks)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
    esac
}
complete -F _husk_completions husk
