#compdef husk
# generated by `husk --print-completion=zsh` -- do not hand-edit; regenerate with that command whenever export's flag table changes.

_husk_skin_value() { _alternative 'value:value:(auto)' 'files:file:_files' }
_husk_anim_value() { _alternative 'value:value:(auto inline none)' 'dirs:directory:_files -/' }
_husk_dir_or_none_value() { _alternative 'value:value:(none)' 'dirs:directory:_files -/' }
_husk_dir_value() { _alternative 'dirs:directory:_files -/' }
_husk_file_or_none_value() { _alternative 'value:value:(none)' 'files:file:_files' }

_husk() {
    local -a subcommands
    subcommands=(
        'export:export a mesh (+ skin/animation) to glTF'
        'info:parse and print an M2 header'
        'dump-chunks:extract misc chunks to JSON'
        'db2-info:parse and print a WDC5 DB2 file'
        'db2-export:convert WDC5 DB2 file(s) to a real SQLite database'
        'db2-build:build husk's own verified knowledge-base DB'
        'blp-export:convert BLP2 texture(s) to PNG'
        'appearance-string:validate/normalize a husk-appearance/1 string'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi

    case ${words[2]} in
        export)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--config[--config]:value:_files' \
                '(-i --input)'{-i,--input}'[the .m2 file to export]:value:_files' \
                '(-o --output)'{-o,--output}'[output .glb path]:value:_files' \
                '--from-list[--from-list]:value:_files' \
                '--output-dir[--output-dir]:value:_files' \
                '(-s --skin)'{-s,--skin}'[a .skin path, or auto]:value:_husk_skin_value' \
                '(-t --textures)'{-t,--textures}'[texture directory, or none]:value:_husk_dir_or_none_value' \
                '--textures-out[directory to also write decoded .png copies to]:value:_husk_dir_value' \
                '--slim-textures[write textures as external files instead of embedding]' \
                '--skin-dir[skin-search directory, or none]:value:_husk_dir_or_none_value' \
                '(-a --anim)'{-a,--anim}'[auto, inline, none, or a directory]:value:_husk_anim_value' \
                '--skel[external .skel path, or none]:value:_husk_file_or_none_value' \
                '--lod[LOD index, or all]:value:(all)' \
                '--bones-dir[bone-correction directory, or none]:value:_husk_dir_or_none_value' \
                '--phys[external .phys path, or none]:value:_husk_file_or_none_value' \
                '--collision[include the collision mesh (off by default)]' \
                '--db2-dir[character DB2 directory (texture-layout or customization)]:value:_husk_dir_value' \
                '--dbd-dir[WoWDBDefs checkout, for --db2-dir column names]:value:_husk_dir_value' \
                '--char-layout-id[a real CharComponentTextureLayoutsID]:value:_files' \
                '--customization-choice-ids[comma-separated ChrCustomizationChoiceID(s)]:value:_files' \
                '--chr-model-id[--chr-model-id]:value:_files' \
                '--creature-display-id[--creature-display-id]:value:_files' \
                '--object-skin-texture-id[--object-skin-texture-id]:value:_files' \
                '--knowledge-db[--knowledge-db]:value:_files' \
                '--listfile[community-listfile.csv snapshot, for FileDataID names]:value:_files' \
                '--listfile-root[corpus root the listfile paths are relative to]:value:_husk_dir_value' \
                '1:model:_files'
            ;;
        info)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '1:model:_files'
            ;;
        dump-chunks)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '1:model:_files'
            ;;
        db2-info)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--rows[--rows]:value:_files' \
                '1:model:_files'
            ;;
        db2-export)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--config[--config]:value:_files' \
                '--dir[--dir]:value:_files' \
                '--dbd-dir[WoWDBDefs checkout, for --db2-dir column names]:value:_husk_dir_value' \
                '1:model:_files'
            ;;
        db2-build)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--config[--config]:value:_files' \
                '--db2-dir[character DB2 directory (texture-layout or customization)]:value:_husk_dir_value' \
                '--dbd-dir[WoWDBDefs checkout, for --db2-dir column names]:value:_husk_dir_value' \
                '--listfile[community-listfile.csv snapshot, for FileDataID names]:value:_files' \
                '(-o --output)'{-o,--output}'[output .glb path]:value:_files' \
                '1:model:_files'
            ;;
        blp-export)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--dir[--dir]:value:_files' \
                '1:model:_files'
            ;;
        appearance-string)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--config[--config]:value:_files' \
                '--validate[--validate]:value:_files' \
                '--db2-dir[character DB2 directory (texture-layout or customization)]:value:_husk_dir_value' \
                '--dbd-dir[WoWDBDefs checkout, for --db2-dir column names]:value:_husk_dir_value' \
                '1:model:_files'
            ;;
    esac
}

_husk "$@"
