# generated by `husk --print-completion=bash` -- do not hand-edit; regenerate with that command whenever export's flag table changes.
_husk_completions() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local subcommands="export info dump-chunks"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$subcommands" -- "$cur"))
        return
    fi

    case "${COMP_WORDS[1]}" in
        export)
            case "$prev" in
                --config)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --input|-i)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --output|-o)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --from-list)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --output-dir)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --skin|-s)
                    COMPREPLY=($(compgen -W "auto" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -f -- "$cur"))
                    return
                    ;;
                --textures|-t)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --textures-out)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --skin-dir)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --anim|-a)
                    COMPREPLY=($(compgen -W "auto inline none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --skel)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -f -- "$cur"))
                    return
                    ;;
                --lod)
                    COMPREPLY=($(compgen -W "all" -- "$cur"))
                    return
                    ;;
                --bones-dir)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -d -- "$cur"))
                    return
                    ;;
                --phys)
                    COMPREPLY=($(compgen -W "none" -- "$cur")); compopt -o filenames 2>/dev/null; COMPREPLY+=($(compgen -f -- "$cur"))
                    return
                    ;;
                --db2-dir)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --dbd-dir)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --char-layout-id)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --customization-choice-ids)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --chr-model-id)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --creature-display-id)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --object-skin-texture-id)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --knowledge-db)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --listfile)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --listfile-root)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --config --input -i --output -o --from-list --output-dir --skin -s --textures -t --textures-out --skin-dir --anim -a --skel --lod --bones-dir --phys --collision --db2-dir --dbd-dir --char-layout-id --customization-choice-ids --chr-model-id --creature-display-id --object-skin-texture-id --knowledge-db --listfile --listfile-root" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        info)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        dump-chunks)
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
    esac
}
complete -F _husk_completions husk
